### PR TITLE
Fix for error "Class 'FacebookAds\Object\Agency' not found"

### PR DESCRIPTION
**Pull request by zoonman**
### Rename src/FacebookAds/Object/Fields/Agency.php to src/FacebookAds/Object/Agency.php

FacebookAds\Object\Page method getAgencies() is broken because composer unable to load this file due to inappropriate path.

Composer raises error `Class 'FacebookAds\Object\Agency' not found`.

### CODE REVIEW

**Comment by jedkirby** [comment]
Bump on this, it's been over 4 years for what is a tiny change. Composer 2.0 will stop autoloading this file, as per their optimised autoloader message:

```Deprecation Notice: Class FacebookAds\Object\Agency located in ./vendor/facebook/php-ads-sdk/src/FacebookAds/Object/Fields/Agency.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201```

Please can we have an update and/or fix, i.e. merge this PR, or rename the current file to be PSR-4 compatible, considering you support PSR-4.

**Comment by andreladocruz** [comment]
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.

**Comment by andreladocruz** [comment]
reopened on #530

**Comment by andreladocruz** [comment]
#530 merged

@zoonman, you can close this PR. =)

**Pull request closed without merging**
