### PR TITLE
Fix namespace

### PR DESCRIPTION
**Pull request by minterior**
Fix namespace of file `src/FacebookAds/Object/Fields/Agency.php`.

### CODE REVIEW

**Comment by Mxiim** [comment]
Hi, can you also mention what problem this is solving?

**Comment by minterior** [comment]
Sure!

That class is raising deprecation notices in `composer install` and potentially it could not be loaded/found in the expected path:
```
Generating optimized autoload files
Deprecation Notice: Class FacebookAds\Object\Agency located in ./vendor/facebook/php-business-sdk/src/FacebookAds/Object/Fields/Agency.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

**Comment by wanleng559** [comment]
แน่นอน

**Comment by jslmariano** [comment]
Why is this blocked? I'm having the same issue, will this be in the next version release?

**Comment by cmgmyr** [comment]
Composer 2.0.0 RC1 was released today https://github.com/composer/composer/releases/tag/2.0.0-RC1, so getting close to the stable release. When will this PR be merged & tagged?

**Comment by retargetingbiz** [comment]
same issue here!

**Comment by cmgmyr** [comment]
Looks like this was fixed in 724fc72953947787fd04efa1e26d33ab259e15f2

**Pull request closed without merging**
